### ISSUE TITLE
How can I export my predictions as a csv file?

### ISSUE THREAD

**Issue by Tobias1234** [weecology/DeepForest#137]
Hi!
I trained a model and reloaded it as below. 
I can see the bounding box predictions in my tiles, but it would be useful with a csv file of prediction boundingbox coordinates. Is it possible? Using geopandas or in another way?

import os
from deepforest import get_data
from deepforest import deepforest
from deepforest import utilities
from deepforest import preprocess
from matplotlib import pyplot as plt

test_model = deepforest.deepforest()

reloaded = deepforest.deepforest(saved_model="C:\\Users\\....\\final_model_c.h5”)

test_model = reload.model("C:\\Users\\....\\final_model_c.h5")

image=reloaded.predict_image("C:\\Users\\...\\data\\orto_194.png", return_plot=True)

plt.imshow(image[...,::-1])
plt.show()

Best regards, Tobias

**Comment by bw4sz** [comment]
Thanks for your issue.

```
image=reloaded.predict_image("C:\Users\...\data\orto_194.png", return_plot=True)
```
I think you mean, return_plot=False.

see https://deepforest.readthedocs.io/en/latest/getting_started.html#predict-a-single-image

Let me know if that helps and close. Feel free to open other issues on how to improve documentation so that other users can find this more intuitive.

**Comment by Tobias1234** [comment]
I works! Thanks!
