### ISSUE TITLE
General questions - How-to accomplish

### ISSUE THREAD

**Issue by olla-dev** [weecology/DeepForest#189]
Hello, 
My questions are rather general  and not related to any performance issues or bugs,

I would like to work on a side project using DeepForest to count olive trees in a region or country based on satellite images (I am trying to get Sentinel 2 images). 
* I downloaded labelme to try it. what annotation format is compatible with deepforest? also is it better to proceed by annotating olive groves first (as trees usually form a matrix shape when in traditional not intensive agriculture) and then annotate individual trees? or is it better to skip the first step ? 
* Once the detection complete, how can I estimate the number of trees? is it the number of squares the library inputs on the original image?

examples: 
![image](https://user-images.githubusercontent.com/42831311/119101979-d971e180-ba19-11eb-8f77-7501dc169897.png)
![image](https://user-images.githubusercontent.com/42831311/119102065-ee4e7500-ba19-11eb-8cc0-96d70703d0ae.png)

Thank you

**Comment by bw4sz** [comment]
Information on label format is here: /orange/ewhite/b.weinstein/generalization/crops/palmyra_test.csv

Its basically a .csv of pascal format. A single row for each box, xmin, ymin, xmax, ymax, label. The number of trees would be the number of predicted boxes. Make sure to play with the non-max suppression threshold since your objects are smaller (lower resolution) then the 0.1cm images used in model training. In my experience, larger image patches (~1000px?) can be useful. There isn't a global solution here, so you'll need to test different image patch size in predict_tile.
