### ISSUE TITLE
Multi class training problem

### ISSUE THREAD

**Issue by Bognar791** [weecology/DeepForest#238]
Hello, Please help me..
I am trying to make multi classification with this project.
How can I made multi class model and using that for this project.
I followed document but no result and happens issue.
I made issue on this long days ago but still not response..
So this project is not supporting mainternance?

**Comment by ethanwhite** [comment]
Hi @Bognar791 - this project is definitely still under active development and being support. As @bw4sz pointed out in (https://github.com/weecology/DeepForest/issues/226) we don't currently support multi-class modeling. This is something that represents a major addition to package and while it is definitely on the road map, it is still months away at this point.

You are of course welcome and encouraged to work on getting multi-class approaches working building on the current model and code base, but doing this well is complicated (which is why we are still working on this from both a scientific and software perspective) and so we won't be able to give you quick and easy solutions to something that isn't currently part of the package. We will help out as time allows, but this is a small academic team with many other responsibilities, meaning that you shouldn't expect quick turnaround on questions related to features that aren't yet implemented.

**Comment by ethanwhite** [comment]
Closing since this is already covered in #232 & #233.

**Comment by Bognar791** [comment]
Thanks for your reply.
I understand what you mean, I will wait until your team makes the multi
classification.
Really thanks.

**Comment by ethanwhite** [comment]
You're welcome. Thanks for your understanding.

**Comment by Bognar791** [comment]
Now I am trying to make multi tree crown detection programming.
I saw your program and I thought I can make my project from your project.
So I made this things. But I am first in deep learning.
Could you please tell to me when your team will make multi class function?
Or if your team will not make, could you give me some help to make multi
class model?

**Comment by ethanwhite** [comment]
As a rough estimate I'd say we'll have something within the next 6 months. It could happen sooner, but I wouldn't plan around anything earlier.

If you need something quickly the best thing that I can suggest is to use the existing deepforest method to identify your crowns and then build a separate machine learning approach that takes the reflectance data within each crown to build a species classification model. That may be easier than successfully training multi-class version deepforest. This paper https://peerj.com/articles/5843/ and the associated citations may give you some ideas for approaches that could be used for the species classification task.

**Comment by Bognar791** [comment]
Really thanks for the reply.
I will wait for your project .. Meantime I will try to make my own project.
Thanks.
