### ISSUE TITLE
Bounding boxes visibility

### ISSUE THREAD

**Issue by aditis1204** [weecology/DeepForest#239]
Hi!
I am using deepforest on colab to detect trees, it works great. But I have an issue, the bounding boxes being generated have a light blue colour and it requires me to zoom in to distinguish and find boxes in the image. Can I change the colour and size of bounding boxes? The image size which I am using is 3000px * 3000px. Any suggestions would be really helpful.

**Comment by ethanwhite** [comment]
Hi @aditis1204! That functionality wasn't available, but I've done some initial work to implement it that you can check out and see if it does what you need. The changes are in #240. You can install them directly using pip with the following command:

```bash
pip install git+https://github.com/weecology/deepforest.git@refs/pull/240/head
```

You should then be able to modify the `predict_*` functions by adding optional `color` and `thickness` arguments to change the color and thickness of the bounding boxes, e.g.,

```python
boxes = model.predict_image(path=image_path, return_plot=True, color=(0, 0, 200), thickness=5)
```

Note that the color tuple is BGR (blue, green red) not RGB (red, green, blue).

This doesn't allow changing the size of the bounding box, since we want the bounding box to stop at the edges of the tree, but it does allow changing it's thickness. Is that what you were looking for?

**Comment by Ruphai** [comment]
Hi @ethanwhite I have a similar issue with my code block but it looks like, we can't access it yet. This is the output I got from my end: 

`Collecting git+https://github.com/weecology/deepforest.git@refs/pull/240/head
  Cloning https://github.com/weecology/deepforest.git (to revision refs/pull/240/head) to /tmp/pip-req-build-o2cneb5q
  Running command git clone -q https://github.com/weecology/deepforest.git /tmp/pip-req-build-o2cneb5q
  WARNING: Did not find branch or tag 'refs/pull/240/head', assuming revision or ref.
  Running command git fetch -q https://github.com/weecology/deepforest.git refs/pull/240/head
  Running command git checkout -q 76531615559c59ee2bdfb59fa1397527eb65a73d
`

**Comment by aditis1204** [comment]
Hi @ethanwhite, Thank you for your reply. I will try to follow your instructions. Yes, I was mainly looking for changing thickness.

**Comment by ethanwhite** [comment]
Glad that helps @aditis1204. The details may change a bit as I work thought refining the changes with @bw4sz, but the functionality should be present along with documentation in the next release. Let's leave the issue open for now while we help @Ruphai get everything working and then we can close it.

**Comment by ethanwhite** [comment]
@Ruphai - I saw the warning you are getting as well, but the installation is still getting the right code because the last line shows the right git commit hash (76531615559c59ee2bdfb59fa1397527eb65a73d). Did you get an image with no bounding boxes or no image at all? If no image at all you may need to add one more line:

```python
plt.show()
```

If you got an image but no bounding boxes can you share the image you made the prediction on?

**Comment by Ruphai** [comment]
Yes @ethanwhite, I got an image with no bounding box. You can find a screen grab of the image below:

![Image_output_without_bounding box](https://user-images.githubusercontent.com/59208190/128875633-62a99153-ddfe-4197-9c34-27d0f8101a37.PNG)

**Comment by ethanwhite** [comment]
Thanks @Ruphai - since this appears unrelated to the changes in this issue can you open a new issue and provide the full set of code you ran (including the imports and any steps prior to running `predict_image`) along with the same description of the problem you've given here?

**Comment by Ruphai** [comment]
Alright. I will do that now. Thank you @ethanwhite

**Comment by ethanwhite** [comment]
Thanks @Ruphai. Closing this issue now.

@aditis1204 - thanks for suggesting this change! It's a nice improvement to the usability of the software.
