### ISSUE TITLE
Will unannotated trees impact training?

### ISSUE THREAD

**Issue by EdwardHiscoke** [weecology/DeepForest#296]
This is not a bug, just a question on the quality of the annotations used to retrain the model for multi-class detection of trees.

We have started creating our own annotations using the base DF model and refining the output annotations by hand and then retraining. Currently only part of all our images annotatedand are for the two classes Spruce and Deciduous with about a thousand of each annotated. 

1. Is it necessary for each tree that one intends to train from a single image to be annotated for training? 
2. Will not annotating all trees in an image impact the resulting model, or will they simply be ignored from training? 
3. Are a thousand annotations per class enough to  retrain a current "Tree" that is a spruce to be recognised as a "Spruce" class?

**Comment by ethanwhite** [comment]
> 1. Is it necessary for each tree that one intends to train from a single image to be annotated for training?

Yes

>     2. Will not annotating all trees in an image impact the resulting model, or will they simply be ignored from training?

Yes, because it will treat the unannotated trees as "not trees" 

>     3. Are a thousand annotations per class enough to  retrain a current "Tree" that is a spruce to be recognised as a "Spruce" class?

It depends on how different it is from other classes. If it's really obvious by eye from the imagery then I think there's a reasonable chance that 1000 annotations might get you close when retraining from the base model. See the recently added docs for how to use the base model for detection while training a multi-class model: https://deepforest.readthedocs.io/en/latest/getting_started.html#multi-class-models

**Comment by EdwardHiscoke** [comment]
Right, having had a first check after a brief 30 epochs training it looks like we are starting to get results. It appears the model has started discerning between more nebulous desciduous tree tops and the spikier coniferous, or at least spiky tree tops.
We'll discuss this on monday with our team and look into creating more annotations. Thanks for the swift reply to my questions!

**Comment by ethanwhite** [comment]
My pleasure. Good luck and let us know (in other issues) if there's anything else we can do to help.
