### ISSUE TITLE
freeze backbone layers to do transfer learning?

### ISSUE THREAD

**Issue by easz** [weecology/DeepForest#325]
will the whole network get further trained/modified when a pre-trained model is trained with new data?
https://deepforest.readthedocs.io/en/latest/getting_started.html#training

isn't it a common practice to freeze backbone network (and train only heads) when doing transfer learning?
what is your experience?

otherwise we may provide an option to freeze backbone on demand. (e.g. `requires_grad = False`)
https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by ethanwhite** [comment]
I'll provide the best response I can, but @bw4sz may want to jump in here as well.

> will the whole network get further trained/modified when a pre-trained model is trained with new data? https://deepforest.readthedocs.io/en/latest/getting_started.html#training

Yes, the current behavior is to train the full network when fine-tuning a pretrained model.

> isn't it a common practice to freeze backbone network (and train only heads) when doing transfer learning? what is your experience?

Yes, but the best choice depends in part on whether you you think you need to change/improve the underlying feature representations or just the application of them in the heads. 

> otherwise we may provide an option to freeze backbone on demand. (e.g. `requires_grad = False`) https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

I agree that having this as an option is a good idea and it fits in with some work that @dassaniansh is doing this summer to directly support multi-class applications of the model (since we want to keep some components of the single class detector, but allow it to be applied to multi-class problems). So, I'm definitely in favor of this.

See also #202.

**Comment by aleksandraradecka1** [comment]
Hello All, 

I went through all the issues on the topic of transfer learning & fine-tuning, and got a bit confused about the current development state. Could you plese confirm/correct the conclusions I made:

1) one-class approach: we can make use of the pretrained model created based on NEON dataset by retraining all layers using our external data, there is however no way to freeze backbone layers and fine-tune only the head part  

2) multi-class approach: we can make use of the backbone part of the pretrained model which is frozen, and only the head part gets trained using external data

I hope I was clear enough. 
Aleksandra

**Comment by bw4sz** [comment]
Can we reverse this question? What's your goal and use case and then we can find the best solution for you.

**Comment by aleksandraradecka1** [comment]
Of course. 

My goal is to create an algorithm which detects the bounding boxes of secondary succession objects (little trees and shrubs in my case) belonging to the main succession species in a particular research area (usually 3-5 species, multi-class problem). I would therefore like to experiment with some "elements" of the model which I consider important for that goal e.g. augmentation, fine-tuning/transfer learning. 

At least knowing precisely what is implemented underneath different functions would be helpful (so that I know what I am doing and what should I search for somewhere else). 

I few days ago I got the permission to share some parts of the data, so I will be eager to show the results as soon as I have them.

**Comment by ethanwhite** [comment]
See #394 for additional discussion. I still think being able to freeze the backbone when calling `use_release()` is a good idea.
