### ISSUE TITLE
More model registry to cometML?

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#380]
https://www.comet.com/site/products/machine-learning-model-versioning/

Comet has a robust set of model registry tools. That allow versioning and archiving. This would be useful if we start to gather more models and versions of models. Currently there isn't alot of iteration in the baseline models, so it might be overkill at the current model. Clearly the current workflow of stashing the model in the git release and checking a local .csv about what model we have used is pretty hacky and bound to break eventually. 

Thoughts @ethanwhite?

**Comment by ethanwhite** [comment]
I definitely think we should move to formal model registry as part of our overall process. Let's just make sure to set it up on the group workspace so that we don't have releases for the same general models in different places depending on who ran that model version. In general I think putting all experiments in the group workspace is better practice for easier collaboration anyway, so if anything this should encourage other good habits.

**Comment by bw4sz** [comment]
An added benefit here is that the github releases and the pypi releases can match. Its odd that they do not match currently.
