### ISSUE TITLE
Detecting crown contours

### ISSUE THREAD

**Issue by aloboa** [weecology/DeepForest#389]
As far as I understand from the results (eg https://visualize.idtrees.org/),
Deepforest output are _rectangles including detected crowns_, rather than
the actual polygons contouring the crowns.
Is this because the input training is also _rectangles including crowns_ or is
there something in the processing that prevents the method to output
crown polygons?
In other words, if we train with delineated crown polygons, would we get crown polygons as output?

**Comment by ethanwhite** [comment]
The algorithm is bounding box based because that's how most computer vision detection algorithms work fundamentally. This is in contrast to most LIDAR based approaches which inherently produce polygons. If you need polygons from image data then you'll need a method that adds a masking phase to the process. We've experimented with some but don't have anything implemented.

If polygons are a priority I recommend checking out https://github.com/PatBall1/detectree2, which uses a mask R-CNN that adds the masking phase and is designed to work on polygon training data.
