### ISSUE TITLE
OMP: Error #15 during Getting Started

### ISSUE THREAD

**Issue by mparent3** [weecology/DeepForest#391]
**Describe the bug**
When loading the current release model after DeepForest installation in R, model = df_model() causes OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

**To Reproduce**
Complete Basic Installation of Using DeepForest from R
Load the current release model
Input
`library(deepforestr)

model = df_model()
model$use_release()`
OMP: Error #15 occurs at model = df_model()

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version and environment : Python in R installed from DeepForest Basic Installation

**Screenshots**

**Additional context**
I am an undergraduate student in Dr. Swenson's lab at the University of Notre Dame and I am setting up DeepForest for the first time to work with his group.

**Comment by ethanwhite** [comment]
Hi @mparent3 - thanks for reporting this. Keeping the R-wrapper up and running has been tricky due to changes in the package that we use for running the core Python package from R. I'm going to spend a bit of time seeing if I can fix it again this weekend, and I'll let you know if I get anywhere, but the easiest thing to do is to use the Python package directly to do the tree detection and then move to R for everything else.

**Comment by mparent3** [comment]
Ok, thank you for the update and for trying to fix it.

**Comment by ethanwhite** [comment]
Notes from work so far:
* I can replicate this error on Windows following the standard install instructions
* Works correctly on Linux with non-reticulate deepforest install
* Works correctly on Linux with reticulate deepforest install
* Likely route forward: https://stackoverflow.com/questions/20554074/sklearn-omp-error-15-initializing-libiomp5md-dll-but-found-mk2iomp5md-dll-a; specifically https://stackoverflow.com/a/59119273/133513

**Comment by ethanwhite** [comment]
@mparent3 - I have a solution for you to try (at least a partial one). Steps 2-4 are just to get rid of the installation that R did for you which is having issues.

1. Install miniconda by downloading and running the executable here https://docs.conda.io/en/latest/miniconda.html Miniconda is a same thing R uses to install Python packages, you're just going to install it yourself. All of the defaults are fine during installation.
2. Launch `Anaconda Prompt` from your start menu
3. Type `conda env list`. This should show one of more environments named `r-miniconda` or `R-MINI...` along with the directories they are created in. The directory is probably something like `C:\Users\yourusername\AppData\Local\r-miniconda.
4. Delete that directory/directories. It may look like multiple but actually just be one. You can do this from the command line while staying in the `Anaconda Prompt` window or from the File Explorer. In the File Explorer you will probably have to type the path into the bar since the AppData directory is hidden. Then rerun `conda env list`. The only thing left should be c:\Users\yourusername\miniconda3.
5. Now, in the `Anaconda Prompt` window, run `pip install deepforest`
6. Restart R and try the Getting Started commands again

This worked for me on the same machine that I used to replicate the issue you encountered, so hopefully this will get you up and running while I figure out how to get R to handle that install in a way that doesn't break things.

**Comment by mparent3** [comment]
Hi @ethanwhite,
It worked! Following those steps exactly got past model = df_model() and I was able to run the predictions for the single image and tile in Getting Started.
Thank you for your help!

**Comment by ethanwhite** [comment]
Awesome! Glad it worked.

Reopening since I'm hoping to create a fix that can be done entirely from R.

**Comment by ethanwhite** [comment]
I just merged a fix to the R-based install instructions that also works:
https://github.com/weecology/deepforestr/commit/e10c158cfa846b2b683d8595336eb04219c9960b

Thanks for reporting the bug @mparent3!
