### ISSUE TITLE
Problem importing main from deepforest

### ISSUE THREAD

**Issue by mloricn2** [weecology/DeepForest#517]
I installed the deepforest library and can successfully import it. I would like to import the main package, but it says in this case, after a few seconds of running, that the kernel has died, and it needs to restart. I have tried several times, but nothing has changed.

 - Macos Ventura 13.3.1
 - Jupyter notebook
 - Python 3.12

<img width="1174" alt="Képernyőfotó 2023-10-15 - 21 22 16" src="https://github.com/weecology/DeepForest/assets/118348832/21ae1947-90fa-4320-8bca-27f9a063ea98">

Thank you for your help!

**Comment by JSpencerPittman** [comment]
I have a Ventura 13.5 let me see if I can recreate it.

**Comment by JSpencerPittman** [comment]
I don't know if this is the actual problem here but I'm wondering if its because of PyTorch. I know PyTorch doesn't currently support Python 3.12 unless you build it from source. 

https://github.com/pytorch/pytorch/issues/110436

You might want to try downgrading python versions. I use 3.10 but PyTorch & DeepForest may also work on 3.11. 
Also maybe try seeing if its how your environment on jupyter is set up.

**Comment by bw4sz** [comment]
Thanks for this issue. and @JSpencerPittman for your help. I agree that python 3.12.0 is probably in front of most packages. It was released on Oct 2. Is there a reason you need this? I wouldn't be surprised if there are issues way upstream of DeepForest. Our tests are on python 3.10 atleast on conda. 

https://github.com/weecology/DeepForest/blob/b612d85bbc9d3f31749653a6f27623a93e6a049a/.github/workflows/Conda-app.yml#L17

I don't know how often this will come up and whether we need to add something to setup.py, but I bet this will get solved by itself in a few months.

**Comment by mloricn2** [comment]
Thank you very much for the answers, it works now with python 3.1.
