### ISSUE TITLE
evaluation score on the test file is 0

### ISSUE THREAD

**Issue by melaineAK** [weecology/DeepForest#73]
**Inspired from the case study in tropical forest, the code is:**

```
model = deepforest.deepforest()
model.use_release()
model.__release_version__
annotation_paths = glob.glob("DeepForest/*.csv")
annotation_list = []
for csv in annotation_paths:
    #get plot name to match to RGB image
    plot_name = re.search("P(\w+).csv",csv).group(1)
    #Where to save cropped images
    crop_dir = "DeepForest/crops/"
    annotations_file = get_data(csv)
    result = preprocess.split_raster(path_to_raster="RetroProj_cropped/RP_2015_P{}.tif".format(plot_name),
                                     annotations_file=annotations_file,
                                     base_dir=crop_dir,
                                     patch_size=800,
                                     patch_overlap=0.05)
    annotation_list.append(result)

train_annotations = pd.concat(annotation_list)

#Split image crops into training and test.
image_paths = train_annotations.image_path.unique()
test_paths = np.random.choice(image_paths, 1)
test_annotations = train_annotations.loc[train_annotations.image_path.isin(test_paths)]
train_annotations = train_annotations.loc[~train_annotations.image_path.isin(test_paths)]


#save to file
#Write window annotations file without a header row, same location as the "base_dir" above.
train_annotations.to_csv(crop_dir + "train.csv",index=False,header=False)
test_annotations.to_csv(crop_dir + "test.csv",index=False,header=False)

annotations_file= crop_dir + "train.csv"
test_file= crop_dir + "test.csv"

model.config["validation_annotations"] = test_file
model.evaluate_generator(test_file)

**Results:**
There are 1 unique labels: ['Tree'] 
Disabling snapshot saving
Running network: N/A% (0 of 1) |         | Elapsed Time: 0:00:00 ETA:  --:--:--WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Running network: 100% (1 of 1) |#########| Elapsed Time: 0:00:05 Time:  0:00:05
Parsing annotations: 100% (1 of 1) |#####| Elapsed Time: 0:00:00 Time:  0:00:00
1174 instances of class Tree with average precision: 0.0000
mAP using the weighted average of precisions among classes: 0.0000
mAP: 0.0000
```

**Example of data :**
**dataP4.csv**
image_path,xmin,ymin,xmax,ymax,label
RP_2015_P4.tif,181,47,192,59,Tree
RP_2015_P4.tif,190,49,200,57,Tree
RP_2015_P4.tif,197,52,204,55,Tree
RP_2015_P4.tif,204,53,211,56,Tree
RP_2015_P4.tif,185,54,199,65,Tree
RP_2015_P4.tif,211,54,223,65,Tree

**test.csv**
RP_2015_P15_0.jpg,327,90,332,95,Tree
RP_2015_P15_0.jpg,226,59,236,65,Tree
RP_2015_P15_0.jpg,235,63,241,71,Tree
RP_2015_P15_0.jpg,218,125,229,134,Tree
RP_2015_P15_0.jpg,262,127,269,133,Tree
RP_2015_P15_0.jpg,255,128,265,136,Tree
RP_2015_P15_0.jpg,232,128,238,136,Tree
RP_2015_P15_0.jpg,226,124,232,130,Tree

**Comment by bw4sz** [comment]
Hey Melaine, totally reasonable mistake, but you are point at the ORIGINAL annotations file. That was for the entire tile. DeepForest cuts that tile into pieces and makes predictions on those pieces. You want the file you created here

```
test_annotations.to_csv(crop_dir + "test.csv",index=False,header=False)
```

The way I could tell is the image_path is to the original tile: RP_2015_P4.tif

Whereas a window image would be labeled with its index RP_2015_P4_1.tif

plus that test.csv has no column names.

**Comment by bw4sz** [comment]
That code looks correct, but i'm doubtful that is the result, let's try looking at some predictions and ground truth? Spatial projection conversion issue? Just a guess, but easiest to look. Something must be invalid in the formatting, one piece of evidence is that the run time is VERY fast?

```
Running network: 100% (1 of 1) |#########| Elapsed Time: 0:00:05 Time:  0:00:05
```
does it really take 5 seconds to run 1174 samples? I'm guessing that its skipping all of them because they are invalid. I'll need to write a better data checker. 

As an example, from that doc

```
model.config["save_path"] = "."
model.evaluate_generator(annotations_file)
```

```
Running network: N/A% (0 of 72) |        | Elapsed Time: 0:00:00 ETA:  --:--:--
There are 1 unique labels: ['Tree'] 
Disabling snapshot saving
Running network: 100% (72 of 72) |#######| Elapsed Time: 0:02:25 Time:  **0:02:25**
Parsing annotations: 100% (72 of 72) |###| Elapsed Time: 0:00:00 Time:  0:00:00
6708 instances of class Tree with average precision: 0.4130
mAP using the weighted average of precisions among classes: 0.4130
mAP: 0.4130
```

**Comment by bw4sz** [comment]
Can i see the tail of test.csv is there just RP_2015_P15_0.jpg or is there RP_2015_P15_1.jpg, RP_2015_P15_2.jpg etc. For whatever reason, evaluate generator is telling me you have just one window.

**Comment by melaineAK** [comment]
Indeed, you're right, there is a problem with test.csv, there is only RP_2015_P15_0.jpg

**Comment by bw4sz** [comment]
I found one error in your code, not sure if its related.

```
    annotations_file = get_data(csv)
```

the get_data function is just to get internal data for the package. You already have the path to csv, its

```
    annotations_file = csv
```

**Comment by melaineAK** [comment]
Ok, from the prediction, it is clearly a projection problem. I will correct that!
![0](https://user-images.githubusercontent.com/19783203/73864773-7d924200-4842-11ea-849d-86c9e24da90c.png)

**Comment by bw4sz** [comment]
Still not seeing any bug in the actual, looking at this again, the reason you just get one window is that you called

```
test_paths = np.random.choice(image_paths, 1)
```
so that checks out. That means you want 1 window for testing. There are probably a couple hundred windows in a tile, so that would be a very small testing set. That will still not explain your result. Looking at what was saved to model.config["save_path"] directory should help. The fact that you have 1174 tree crowns in a single 800 pixel window suggests something wrong with the formatting. Since the imagery is 0.1m that would be 1174 in a 80m area, or 14 crowns per square meter. Something about how you created the original .csv seems off. 

Did you forget to multiply the cell size to convert from meters to pixels when creating your .csv file? Just a guess.

**Comment by bw4sz** [comment]
Got it. Glad we figured it our.

Btw, the reason you just get one window is that you called


```
test_paths = np.random.choice(image_paths, 1)
```
so that checks out. That means you want 1 window for testing. There are probably a couple hundred windows in a tile, so that would be a very small testing set. That will still not explain your result. Looking at what was saved to model.config["save_path"] directory should help. The fact that you have 1174 tree crowns in a single 800 pixel window suggests something wrong with the formatting. Since the imagery is 0.1m that would be 1174 in a 80m area, or 14 crowns per square meter. 

Looking at the image did you forget to multiply the cell size to convert from meters to pixels when creating your .csv file? Just a guess. The annotations file is the image coordinates, so the topleft is 0,0. Let me know if I can make the docs better in anyway, or if I can make a new function to help in data conversion. Whatever I can do to make it easier.

**Comment by bw4sz** [comment]
I made a function (need to install geopandas), that might help. This is lightly tested, but I like the idea of including it. Convert from a shapefile to annotations

https://gist.github.com/bw4sz/e2fff9c9df0ae26bd2bfa8953ec4a24c

**Comment by melaineAK** [comment]
Indeed I forgot to convert from meters to pixel. Thanks for your help, the function shapefile_to_annotations works perfectly.
