### ISSUE TITLE
Torchvision or Pytorch Lightning?

### ISSUE THREAD

**Issue by camappel** [weecology/DeepForest#753]
**Describe the bug**
The [documentation](https://deepforest.readthedocs.io/en/latest/landing.html) states that "DeepForest is built on the object detection module from the [torchvision package](http://pytorch.org/vision/stable/index.html)". However, it appears that it is a Pytorch Lightning object. Has DeepForest moved from torchvision to Lightning? Or are these not mutually exclusive? I believe it was implemented in Tensorflow in v1.14

**To Reproduce**
The deepforest class in [main.py](https://github.com/weecology/DeepForest/blob/main/deepforest/main.py) inherits from pl.LightningModule.

*Also*

**Describe the bug**
In the CropModel [.html](https://deepforest.readthedocs.io/en/latest/CropModels.html), it says that "Beginning in version 1.4.0, the CropModel class can be used in conjunction with predict_tile and predict_image methods". 

It looks like I'm using version 1.3.3, even after implementing the changes in #745. However, the CropModel class is still in the model.py file and the predict_tile function in the deepforest class contains cropModel as an argument.

I don't think it's particularly important as I have all the functionality of the latest version, but I'm not sure why it says it's v1.3.3

**To Reproduce**
```
pip show DeepForest             
Name: deepforest
Version: 1.3.3

from deepforest.model import CropModel
model = CropModel()
```

Thanks!

**Comment by bw4sz** [comment]
Hey @camappel can you tell me a bit more about your project and yourself in terms of your needs. 

Torchvision and pytorch lightning are both built on top of pytorch. Pytorch lightning in particular is just a pytorch wrapper, it should be considered as literally pytorch. DeepForest hasn't been in tensorflow for several years, since 1.0. Where did you see that? Perhaps a very old paper? I'd want to hunt down those references to prevent confusion. So, no there is no conflict at all between torchvision and pytorch lightning, its a very common combination of packages, for example see torchgeo. 

Your second question on the CropModel is the difference between the docs which are generated on the main branch and the  pip version which is behind at 1.3.3. @ethanwhite and @henrykironde this is the second user to note this, its probably time to talk about deploying docs off the release? Instead of on main. @henrykironde can you make an issue here and add [Discussion] tag. @camappel if you want to the bleeding edge, install from the git repo, either clone the [repo](https://deepforest.readthedocs.io/en/latest/CONTRIBUTING.html#getting-started) or pip install from [git](https://gist.github.com/javrasya/e95ade856ff42e4649972f8a54368459). I sense that after my collaborators and I discuss, 1.4.0 will be up on pip next week. 

Please close unless there are further needs.

**Comment by henrykironde** [comment]
Thanks @bw4sz, We are working on that, in fact we activated 1.3.3. I am working on clarifying those doc versions.

**Comment by ethanwhite** [comment]
Existing docs issue is here for reference: https://github.com/weecology/DeepForest/issues/746

**Comment by bw4sz** [comment]
Great, I think this can be closed.

**Comment by camappel** [comment]
Thanks very much for the explanation. TensorFlow being used in 1.14 was a guess, as I knew it had been used previously but wasn't sure which version.

For context, I'm working on another Environmental Data Science [notebook](https://github.com/alan-turing-institute/environmental-ds-book/issues/251) for DeepForest, since the last notebook is from 2022 and didn't include the CropMode. 

Closing this issue - thank you!
